### ISSUE TITLE
Breaking change on v0.0.28

### ISSUE THREAD

**Issue by oltodo** [relayjs/eslint-plugin-relay#44]
v0.0.28 release has involved to update `graphql` dep from v0.13.0 to v14.0.0. The problem with the latter version it doesn't support node 9.x:

> error graphql@14.0.0: The engine "node" is incompatible with this module. Expected version "6.x || 8.x || >= 10.x".

So, I think this evolution would have deserved at least a minor version.

**Comment by kassens** [comment]
Ugh, annoying :(

I don't think there's much we can do after the fact anymore?
