### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by nirvdrum** [relayjs/eslint-plugin-relay#91]
I'm working on an overdue migration from TSLint to ESLint due to the former's deprecation in favor of the latter. I had been using a plugin called [tslint-plugin-relay](https://github.com/relay-tools/tslint-plugin-relay), which ported rules from this project over to TypeScript. Is there any interest in supporting TypeScript rules to parallel the Flow rules? If so, I'd be happy to work on upstreaming work from _tslint-plugin-relay_. If not, I can work on separate plugin instead.

**Comment by nirvdrum** [comment]
The project at large works with TypeScript, but `plugin:relay/recommended` enables `relay/generated-flow-types`, which doesn't work in any non-Flow project. That needs to be explicitly disabled in the ESLint `rules` configuration. I was inquiring about a parallel rule set to `relay/generated-flow-types` that would provide a similar type of linting with TypeScript in mind.

**Comment by matthieu-foucault** [comment]
I do have an issue where `relay/unused-fields` does not output information about the line number, making the warning easy to miss when only looking at the IDE

**Comment by llldar** [comment]
I'll try with PR #115, no promises

**Comment by reckter** [comment]
I managed to get it working in #128, thanks to @llldar work in #115 :D

**Comment by gajus** [comment]
What dose `generated-flow-types` do?

**Comment by alloy** [comment]
#128 has been merged
